### ISSUE TITLE
Initial site

### ISSUE THREAD

**Issue by evykassirer** [StarConUW/starconuw.github.io#1]
I'm gonna say due in a week (May 15) but that's obviously flexible depending on what you have going on

About section:

- [x] mission statement
- [x] maybe a little bit about the meaning behind the name *con (not urgent)

- [x] page with code of conduct:  https://github.com/StarConGitHub/code-of-conduct/blob/master/code-of-conduct-v0.md  ( there are some missing pieces )

- [x] contact Info:  exec@starcon.io, https://twitter.com/StarConUW, Facebook page will be made soon and I'll send that over

- [ ] we need to have HTTPS - this might be relevant: https://github.com/blog/2186-https-for-github-pages

**Comment by arshiamufti** [comment]
@evykassirer since we moved over to our custom domain, we don't have https anymore

**Comment by evykassirer** [comment]
Hoooo boy

https://github.com/isaacs/github/issues/156

Looks like we can't do GitHub Pages + custom domain + https (unless I'm missing something). Gotta pick 2/3. We already paid for the domain. How important is https for our purposes? If it's really important we might have to use something else. But I'd rather not.

Anna might feel differently though

**Comment by arshiamufti** [comment]
i think that since this just a static site it's fine (but not ideal) to forgo https. If the first run of our conference goes well and we decide to hold it again, hopefully github will have added this feature or we'll be able to host our website somewhere else and enable https.
