### ISSUE TITLE
Links to HelloCon and !!con on About page are broken

### ISSUE THREAD

**Issue by trishume** [StarConUW/starconuw.github.io#14]
The HelloCon link is missing an `http://` and the `!!con` link has an empty `href`.

Also I can't select the text, which makes me sad, but isn't a big deal.

**Comment by evykassirer** [comment]
Thank you! I meant to check all the links before deploying, so woooops.

fixed links with 032198c

looking into what the css thing in the template code is taking away selecting text and seeing if I can override it

**Comment by evykassirer** [comment]
OMG SO SNEAKY you can select text but the background colour of selecting is the same as the regular background!

**Comment by evykassirer** [comment]
...and turns out I actually added that without knowing what it was >.> 

d2b8ab7bc21bd4c356 fixes it (though for some reason the style from the template is still there, but oh well good enough)
