### ISSUE TITLE
Add Anna's contact info to speaker page

### ISSUE THREAD

**Issue by annalorimer** [StarConUW/starconuw.github.io#18]
Can we add my contact info (anna.lorimer@edu.uwaterloo.ca) to the speaker page? I doubt anyone has any questions at this point, but just in case.

**Comment by arshiamufti** [comment]
sgtm 👍

**Comment by evykassirer** [comment]
Do you want any blurb to go with it? Or just like the sponsor page

**Comment by annalorimer** [comment]
"If you have any questions, please email ..."
