### ISSUE TITLE
Add privacy information to Contact Us form 

### ISSUE THREAD

**Issue by annalorimer** [StarConUW/starconuw.github.io#19]
We'll keep their message and contact info private etc.

**Comment by evykassirer** [comment]
if you want me to change it from what I did, lemme know

**Comment by annalorimer** [comment]
So, I know that the CSC had to change their CoC to comply with campus police i.e they had to change their policy to keeping information private within the extent of the law. (Which is shitty, but it's the law). I have no idea if we have to comply with that or not. 

Either way I would specifically say that we won't share their contact information or the contents with anyone other than conference exec.
