### ISSUE TITLE
Move Prospectus up on the About page

### ISSUE THREAD

**Issue by annalorimer** [StarConUW/starconuw.github.io#37]
It's important enough that a user shouldn't have to scroll that far.

**Comment by arshiamufti** [comment]
I would also put it under its own section.

**Comment by annalorimer** [comment]
Like its own page? It's under its own header rn.

**Comment by evykassirer** [comment]
It'll be its own page eventually (as in, the link to it will be `/prospectus`) 

where on the about page should it go? the average viewer won't want to read it - it's more of an in depth about

**Comment by arshiamufti** [comment]
i think between inspiration and "our name" ?

**Comment by evykassirer** [comment]
done - in the same PR - can you give it an extra look?
